# Generated by Django 3.1.6 on 2021-02-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL2'),
        ),
    ]
